


mqtt:
  address: '192.168.1.55'


bases:
  - id: 'raspberrypi2b'
    devises:
      - id: 'rasp2bBME280'
        vendor: 'Bosch'
        model: 'Senser BME280'
        parameters:
          - name: 'temperature'
            parameter_type: 'senser'
            description: 'Temperature in ºC'
            type: 'numeratic'
            unit: 'ºC'
            value_max: 100
            value_min: -100
            icon: 'mdi:temperature-celsius'
          - name: 'humidity'
            parameter_type: 'senser'
            description: 'Humidity in %'
            type: 'numeratic'
            unit: '%'
            value_max: 100
            value_min: 0
            icon: 'mdi:water'
          - name: 'pressure'
            parameter_type: 'senser'
            description: 'Pressure in mm'
            type: 'numeratic'
            unit: 'mm'
            value_max: 2000
            value_min: 0
            icon: ''
      - id: 'rasp2bMercury20x'
        vendor: 'Incotex'
        model: 'Meter Mercury20x'
        parameters:
          - name: 'voltage'
            description: 'Voltage in V'
            parameter_type: 'senser'
            type: 'numeratic'
            unit: 'V'
            value_max: 400
            value_min: 0
            icon: ''
          - name: 'current'
            parameter_type: 'senser'
            description: 'Current in A'
            type: 'numeratic'
            unit: 'A'
            value_max: 300
            value_min: 0
            icon: ''
          - name: 'power'
            parameter_type: 'senser'
            description: 'Power in W'
            type: 'numeratic'
            unit: 'W'
            value_max: 10000
            value_min: 0
            icon: ''
          - name: 'switcher'
            parameter_type: 'switcher'
            type: 'switch'
            endpoint: "switcher",
            features:
              -  "access":7,
                 "description":"On/off state of the switch",
                 "endpoint":"switcher",
                 "name":"state",
                 "property":"state_switcher",
                 "type":"binary",
                 "value_off":"OFF",
                 "value_on":"ON",
                 "value_toggle":"TOGGLE"






bases1:
  - id: <%= base_id = 'raspberrypi2b' %>
    devises:
      - id: <%= device_id = 'rasp2bBME280' %>
        vendor: <%= vendor = 'Bosch' %>
        model: <%= device_model = 'Senser BME280' %>
        parameters:
          -  main:
               name: 'temperature'
               description: 'Temperature in ºC'
               type: 'numeratic'
               unit: 'ºC'
               value_max: 100
               value_min: -100
               icon: 'mdi:temperature-celsius'
          config_1:
            availability:
              - topic: <%= "#{base_id}/bridge/state" %>
            device:
              identifiers:
                - <%= "#{base_id}_#{device_id}" %>
              manufacturer: <%= vendor %>
              model: <%= device_model %>
              name: <%= device_id %>
            device_class: <%= senser_name = 'temperature' %>
            json_attributes_topic: <%= "#{base_id}/#{device_id}" %>
            name: <%= "#{device_id} #{senser_name}" %>
            state_topic: <%= "#{base_id}/#{device_id}" %>
            unique_id: <%= "#{base_id}_#{device_id}_#{senser_name}" %>
            value_template: "{{ value_json.<%= senser_name %> }}"
            unit_of_measurement: 'ºC'
          device_topic:
            access: 1
            description: "Remaining battery in %"
            name: "battery"
            property: "battery"
            type": "numeric"
            unit": "%"
            value_max: 100
            value_min: 0

          - name: 'temperature'
            description: 'Temperature in ºC'
            type: 'numeratic'
            unit: 'ºC'
            value_max: 100
            value_min: -100
            icon: 'mdi:temperature-celsius'
          - name: 'humidity'
            description: 'Humidity in %'
            type: 'numeratic'
            unit: '%'
            value_max: 100
            value_min: 0
            icon: 'mdi:water'
          - name: 'pressure'
            description: 'Pressure in mm'
            type: 'numeratic'
            unit: 'mm'
            value_max: 2000
            value_min: 0
            icon: ''

