

mqtt:
  address: '192.168.1.55'


bases:
  - id: 'raspberrypi2b'
    devises:
      - id: 'rasp2bBME280'
        vendor: 'Bosch'
        model: 'Senser BME280'
        parameters:
          - name: 'temperature'
            parameter_type: 'sensor'
            description: 'Temperature in ºC'
            type: 'numeratic'
            unit: 'ºC'
            value_max: 100
            value_min: -100
            icon: 'mdi:temperature-celsius'
          - name: 'humidity'
            parameter_type: 'sensor'
            description: 'Humidity in %'
            type: 'numeratic'
            unit: '%'
            value_max: 100
            value_min: 0
            icon: 'mdi:water'
          - name: 'pressure'
            parameter_type: 'sensor'
            description: 'Pressure in mm'
            type: 'numeratic'
            unit: 'mm'
            value_max: 2000
            value_min: 0
            icon: ''
      - id: 'rasp2bMercury20x'
        vendor: 'Incotex'
        model: 'Meter Mercury20x'
        parameters:
          - name: 'voltage'
            description: 'Voltage in V'
            parameter_type: 'sensor'
            type: 'numeratic'
            unit: 'V'
            value_max: 400
            value_min: 0
            icon: ''
          - name: 'current'
            parameter_type: 'sensor'
            description: 'Current in A'
            type: 'numeratic'
            unit: 'A'
            value_max: 300
            value_min: 0
            icon: ''
          - name: 'power'
            parameter_type: 'sensor'
            description: 'Power in W'
            type: 'numeratic'
            unit: 'W'
            value_max: 10000
            value_min: 0
            icon: ''
          - name: 'switcher'
            parameter_type: 'switch'
            type: 'switch'
            endpoint: "switcher"
            features:
              - "access": 7
                "description": "On/off state of the switch"
                "endpoint": "switcher"
                "name": "state"
                "property": "state_switcher"
                "type": "binary"
                "value_off": "OFF"
                "value_on": "ON"
                "value_toggle": "TOGGLE"






