mqtt:
  address: '192.168.1.55'

bases:
  - id: 'raspberrypi2b'
    devises:
      - id: 'rasp2bBME280'
        vendor: 'Bosch'
        model: 'Senser BME280'
        parameters:
          - name: 'temperature'
            description: 'Temperature in ºC'
            type: 'numeratic'
            unit: 'ºC'
            value_max: 100
            value_min: -100
            icon: 'mdi:temperature-celsius'
          - name: 'humidity'
            description: 'Humidity in %'
            type: 'numeratic'
            unit: '%'
            value_max: 100
            value_min: 0
            icon: 'mdi:water'
          - name: 'pressure'
            description: 'Pressure in mm'
            type: 'numeratic'
            unit: 'mm'
            value_max: 2000
            value_min: 0
            icon: ''
      - id: 'rasp2bMercury20x'
        vendor: 'Incotex'
        model: 'Meter Mercury20x'
        parameters:
          - name: 'voltage'
            description: 'Voltage in V'
            type: 'numeratic'
            unit: 'V'
            value_max: 400
            value_min: 0
            icon: ''
          - name: 'current'
            description: 'Current in A'
            type: 'numeratic'
            unit: 'A'
            value_max: 300
            value_min: 0
            icon: ''
          - name: 'power'
            description: 'Power in W'
            type: 'numeratic'
            unit: 'W'
            value_max: 10000
            value_min: 0
            icon: ''
